// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/service.proto

/*
Package scriptumproto is a generated protocol buffer package.

It is generated from these files:
	rpc/service.proto

It has these top-level messages:
	Document
	NewDocumentResponse
	DeleteDocumentRequest
	DeleteDocumentResponse
*/
package scriptumproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type NewDocumentResponse struct {
	Err        string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	DocumentId string `protobuf:"bytes,2,opt,name=document_id,json=documentId" json:"document_id,omitempty"`
}

func (m *NewDocumentResponse) Reset()                    { *m = NewDocumentResponse{} }
func (m *NewDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*NewDocumentResponse) ProtoMessage()               {}
func (*NewDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewDocumentResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *NewDocumentResponse) GetDocumentId() string {
	if m != nil {
		return m.DocumentId
	}
	return ""
}

type DeleteDocumentRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *DeleteDocumentRequest) Reset()                    { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()               {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteDocumentRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type DeleteDocumentResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteDocumentResponse) Reset()                    { *m = DeleteDocumentResponse{} }
func (m *DeleteDocumentResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentResponse) ProtoMessage()               {}
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteDocumentResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "blaedj.scriptum.proto.Document")
	proto.RegisterType((*NewDocumentResponse)(nil), "blaedj.scriptum.proto.NewDocumentResponse")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "blaedj.scriptum.proto.DeleteDocumentRequest")
	proto.RegisterType((*DeleteDocumentResponse)(nil), "blaedj.scriptum.proto.DeleteDocumentResponse")
}

func init() { proto.RegisterFile("rpc/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2a, 0x48, 0xd6,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4d,
	0xca, 0x49, 0x4c, 0x4d, 0xc9, 0xd2, 0x2b, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0x29, 0xcd, 0x85, 0x08,
	0x2b, 0x99, 0x70, 0x71, 0xb8, 0xe4, 0x27, 0x97, 0xe6, 0xa6, 0xe6, 0x95, 0x08, 0x89, 0x70, 0xb1,
	0x96, 0x64, 0x96, 0xe4, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x42,
	0x5c, 0x2c, 0x49, 0xf9, 0x29, 0x95, 0x12, 0x4c, 0x60, 0x41, 0x30, 0x5b, 0xc9, 0x83, 0x4b, 0xd8,
	0x2f, 0xb5, 0x1c, 0xa6, 0x31, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x80, 0x8b,
	0x39, 0xb5, 0xa8, 0x08, 0xaa, 0x1d, 0xc4, 0x14, 0x92, 0xe7, 0xe2, 0x4e, 0x81, 0xaa, 0x8a, 0xcf,
	0x4c, 0x81, 0x9a, 0xc1, 0x05, 0x13, 0xf2, 0x4c, 0x51, 0xd2, 0xe6, 0x12, 0x75, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x45, 0x18, 0x56, 0x58, 0x9a, 0x5a, 0x5c, 0x02, 0xb2, 0xb6, 0xb4, 0x34, 0x33, 0x05,
	0x6a, 0x18, 0x98, 0xad, 0xa4, 0xc5, 0x25, 0x86, 0xae, 0x18, 0x97, 0xcd, 0x46, 0x77, 0x18, 0xb9,
	0xf8, 0x83, 0xa1, 0x7e, 0x0d, 0x86, 0x84, 0x84, 0x50, 0x14, 0x17, 0x37, 0x92, 0xb3, 0x85, 0xe4,
	0xf5, 0xb0, 0x86, 0x89, 0x1e, 0x4c, 0x81, 0x94, 0x16, 0x0e, 0x05, 0xd8, 0xfc, 0x9e, 0xcb, 0xc5,
	0x87, 0xea, 0x36, 0x21, 0x1d, 0x5c, 0xc6, 0x63, 0xf3, 0xaf, 0x94, 0x2e, 0x91, 0xaa, 0x21, 0xd6,
	0x39, 0xf1, 0x47, 0xf1, 0xc2, 0x14, 0x82, 0xd5, 0x25, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0x60, 0x6d, 0x50, 0xfb, 0x01, 0x00, 0x00,
}
